### ISSUE TITLE
Dropbox Links Disabled

### ISSUE THREAD

**Issue by Scrxtchy** [lavanoid/lavanoid.github.io#2]
Unable to fetch releases from the service as the file host is no longer allowing users access to the files due to is being accessed so much by the community.
Unsure on a short-term solution other than waiting it out, but a long-term solution is something worth considering as this may become a burden to deal with

![](https://jii.moe/VJbjeN4De.png)

**Comment by lavanoid** [comment]
I am aware. I'm considering of hosting the files on a dedicated server, which has TB's worth of Bandwidth.

Give me a few days. I'll have to configure everything when I'm not being raped by college work.

**Comment by Scrxtchy** [comment]
Thanks for the reply, happy to see it already under consideration.
Good luck with your school work :)

**Comment by lavanoid** [comment]
Fixed.
